/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tiger_jni_HelloNative */

#ifndef _Included_com_tiger_jni_HelloNative
#define _Included_com_tiger_jni_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tiger_jni_HelloNative
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tiger_jni_HelloNative_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
